using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TAPBot
{

    // a simple decorator for the SpinAction to support saving the deals generated by spin to a file
    class SaveSpinAction : ChatBotAction
    {
        // the action we are decorating, we'll forward the Execute request to it in this classes execute operation
        SpinAction spinner;

        public SaveSpinAction(string friendId, string chatId, SpinAction spinner) : base(friendId, null)
        {
            this.spinner = spinner;
        }


        public override void Execute()
        {
            spinner.Execute();
            results = spinner.GetMessage();

            // write to file here

            messageAvailable = true;
            success = true;
        }
    }
}
